CREATE TABLE IF NOT EXISTS PRODUCTS
(
    PRODUCT_ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    ACC_NUMBER VARCHAR(255),
    BALANCE NUMERIC(19, 4),
    TYPE VARCHAR(50),
    CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT fk_type FOREIGN KEY (TYPE) REFERENCES PRODUCT_DICTIONARY(CODE)
);

COMMENT ON TABLE PRODUCTS IS 'Продукты клиента';